[project]
name = "d2-coursecode"
version = "0.1.0"
description = ""
authors = [
    {name = "Siamak Khatami",email = "khatami.sia@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all] (>=0.141.1,<0.142.0)",
    "passlib[all] (>=1.7.4,<2.0.0)",
    "bcrypt (>=3.2,<4.1)",
    "python-jose (>=3.5.0,<4.0.0)",
    "sqlalchemy (>=2.1.1,<3.0.0)",
    "psycopg2-binary (>=2.9.13,<3.0.0)",
    "alembic (>=1.20.0,<2.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-html (>=4.2.0,<5.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


# Pytest configuration options
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["test"]
