"""initing dg

Revision ID: 5a2e3859781b
Revises: 
Create Date: 2026-09-29 16:24:32.586173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from utils.constants import Tables, Columns


# revision identifiers, used by Alembic.
revision: str = '5a2e3859781b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(Tables.ADMIN,
    sa.Column(Columns.ADMIN_ID, sa.Integer(), nullable=False, primary_key=True, index=True),
    sa.Column(Columns.EMAIL, sa.String(), nullable=False, unique=True, index=True),
    sa.Column(Columns.NAME, sa.String(), nullable=False),
    sa.Column(Columns.HASHED_PASSWORD, sa.String(), nullable=False),
    sa.Column(Columns.CREATED_AT, sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column(Columns.UPDATED_AT, sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column(Columns.DELETED_AT, sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email'), table_name=Tables.ADMIN)
    op.drop_index(op.f('ix_admin_admin_id'), table_name=Tables.ADMIN)
    op.drop_table(Tables.ADMIN)
    # ### end Alembic commands ###
