"""addig a note column

Revision ID: feb1d4248d39
Revises: 5a2e3859781b
Create Date: 2026-09-29 16:28:13.137785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb1d4248d39'
down_revision: Union[str, Sequence[str], None] = '5a2e3859781b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'note')
    # ### end Alembic commands ###
