FROM nginx:latest

# Nginx always looks at this /etc/nginx/nginx.conf for its configuration.
# So we copy our conf from local machine into the image to build it correctly.
COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./nginx.crt /etc/ssl/certs/nginx.crt
COPY ./nginx.key /etc/ssl/private/nginx.key


EXPOSE 80
EXPOSE 443


CMD ["nginx", "-g", "daemon off;"]